version: 2.1

jobs:
  # running commands on a basic image
  Build:
    docker:
      - image: cimg/python:3.10
        
    steps:
      - run:
          name: build
          command: python3 manage.py runserver 0.0.0.0:8000
          ports:
            - "8000:8000"
  # fetching code from the repo
  Test-Lintting:
    docker:
      - image: cimg/python:3.10
        
    steps:
      - checkout
      - run:
          name: Testing and lintting my code
          command: |
            flake8
            pytest
  # running a node container
  Containerization:
    build:
    run:
    push:
    pull:
    run:
      
  Deploy:
    docker:
      - image: cimg/python:3.10
        
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
workflows:
  Workflow-OC-Lettings:
    jobs:
      - Build
      - Test-Lintting:
          requires:
            - Build
      - Deploy:
          requires:
            - Test-Lintting
