version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    step: 
      - checkout
      - run: my-build-commands
  linting:
      docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
      - run: flake8
  test:
    docker:
      - image: alpine:3.15
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
    steps:
      - checkout
      - run: pytest
  deploy:
      docker:
        - image: alpine:3.15
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_PASSWORD
     steps:
      - checkout
      - run: my-deploy-commands
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build:
      - linting:
          requires:
            - build
      - test:
          requires:
            - linting
      - deploy:
          requires:
            - test
