version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  build-test-lintting:
    docker:
      # available images on: https://circleci.com/developer/images/image/cimg/python
      - image: python:3.8-slim-buster

    steps:
      - checkout
      - run:
          name: Create and activate a virtual environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
          when: always
      - run:
          name: Install packages
          command: pip install -r requirements.txt
          when: always
      - run:
          name: Migrate the database
          command: python manage.py migrate
          when: always
      - run:
          name: Test my application
          command: |
            . venv/bin/activate
            pytest
          when: always
      - run:
          name: Linting
          command: |
            . venv/bin/activate
            flake8
          when: always
           
  dockerization :
    machine : true
    steps:
      - checkout
      # Docker connection
      - run: echo "$DOCKERHUB_PAT" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      # Build the Docker image from Docker hub using the environment variables defined in my circle ci setting
      - run: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_NAME_IMAGE:$"0.1.${CIRCLE_BUILD_NUM}" .
      # Push this Docker image into Docker hub
      - run: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_NAME_IMAGE:$"0.1.${CIRCLE_BUILD_NUM}"
      # push image under Heroku
      - run: docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_NAME_IMAGE registry.heroku.com/HEROKU_APP_NAME/web
      - run: docker push registry.heroku.com/HEROKU_APP_NAME/web
      #- run: docker pull $DOCKERHUB_USERNAME/$DOCKERHUB_NAME_IMAGE
      #- run: docker tag $DOCKERHUB_USERNAME/$DOCKERHUB_NAME_IMAGE registry.heroku.com/HEROKU_APP_NAME/web



  deployment:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a $HEROKU_APP_NAME web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a $HEROKU_APP_NAME web
            

            

# define the workflow with the desired order to launch each job
workflows:
  version: 2
  Python-OC-Lettings-FR:
    jobs:
      - build-test-lintting
      - dockerization:
          requires:
            - build-test-lintting
          filters:
            branches:
              only: master
      - deployment:
          requires:
            - dockerization
          filters:
            branches:
              only: master

