version: 2.1

jobs:
  # running commands on a basic image
  Build:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: lintting
          command: |
            echo 'lintting'
            flake8
  # fetching code from the repo
  Test:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Testing my code
          command: |
            echo 'Test in progress'
            pytest
  # running a node container
  Deploy:
    docker:
      - image: cimg/node:17.2
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - run:
          name: Running the Node Container
          command: |
            node -v
workflows:
  Example-Workflow:
    jobs:
      - Build
      - Test:
          requires:
            - Build
      - Deploy:
          requires:
            - Test
